version: "3"
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/bitnami/mongodb/data
    environment:
      MONGODB_DATABASE: errors
      MONGODB_USERNAME: test
      MONGODB_PASSWORD: test
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  mongodb-logger:
    image: guestros/mongodb-logger:latest
    build: .
    depends_on: 
      mongodb:
        condition: service_healthy
    environment: 
      MONGODB_HOST: mongodb
      MONGODB_DB: errors
      MONGODB_USER: test
      MONGODB_PASSWORD: test
      AUTH_PW: apppassword
    ports:
      - "5000:5000"

volumes:
  mongodb-data: